# Generated by Django 5.2.4 on 2025-08-15 19:22

import django.core.validators
import django.db.models.deletion
import run.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('run_type', models.CharField(choices=[('RUN', 'Run'), ('EASY', 'Easy'), ('TEMPO', 'Tempo'), ('INTERVAL', 'Interval'), ('RECOVERY', 'Recovery'), ('FARTLEK', 'Fartlek'), ('LONG', 'Long'), ('RACE', 'Race'), ('OTHER', 'Other')], max_length=10)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('pace_min_km', models.CharField(max_length=5, validators=[run.models.validate_mm_ss])),
                ('heart_rate', models.CharField(blank=True, max_length=20)),
                ('zone', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
