# Generated by Django 5.2.4 on 2025-08-18 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_zone1_min', models.PositiveIntegerField(default=108)),
                ('hr_zone1_max', models.PositiveIntegerField(default=133)),
                ('hr_zone2_min', models.PositiveIntegerField(default=134)),
                ('hr_zone2_max', models.PositiveIntegerField(default=148)),
                ('hr_zone3_min', models.PositiveIntegerField(default=149)),
                ('hr_zone3_max', models.PositiveIntegerField(default=158)),
                ('hr_zone4_min', models.PositiveIntegerField(default=159)),
                ('hr_zone4_max', models.PositiveIntegerField(default=166)),
                ('hr_zone5_min', models.PositiveIntegerField(default=167)),
                ('hr_zone5_max', models.PositiveIntegerField(default=193)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
