# Generated by Django 5.2.4 on 2025-08-21 16:43

import django.core.validators
import django.db.models.deletion
import run.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('run_type', models.CharField(choices=[('RUN', 'Run'), ('EASY', 'Easy'), ('TEMPO', 'Tempo'), ('INTERVAL', 'Interval'), ('RECOVERY', 'Recovery'), ('FARTLEK', 'Fartlek'), ('LONG', 'Long'), ('RACE', 'Race'), ('OTHER', 'Other')], max_length=10)),
                ('distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('pace_target', models.CharField(blank=True, max_length=5, validators=[run.models.validate_mm_ss])),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='run.trainingplan')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
