# Generated by Django 5.2.4 on 2025-08-21 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_trainingplan_plannedrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone1_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone1_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone2_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone2_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone3_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone3_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone4_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone4_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone5_max',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hr_zone5_min',
        ),
        migrations.CreateModel(
            name='HeartRateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_number', models.PositiveIntegerField()),
                ('hr_min', models.PositiveIntegerField()),
                ('hr_max', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='run.profile')),
            ],
            options={
                'ordering': ['zone_number'],
                'unique_together': {('profile', 'zone_number')},
            },
        ),
    ]
