# Generated by Django 5.2.4 on 2025-08-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0005_tag_run_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedrun',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='run.trainingplan'),
        ),
    ]
